export const COUNTRY_OF_INCORPORATION_OPTIONS = [
  'Singapore',
  'Brunei',
  'Cambodia',
  'Indonesia',
  'Laos',
  'Malaysia',
  'Myanmar',
  'Philippines',
  'Thailand',
  'Vietnam',
  'United States',
  'Canada',
  'United Kingdom',
  'Ireland',
  'Germany',
  'France',
  'Italy',
  'Spain',
  'Netherlands',
  'Switzerland',
  'Sweden',
  'Norway',
  'Denmark',
  'Finland',
  'Belgium',
  'Austria',
  'Portugal',
  'Australia',
  'New Zealand',
  'China',
  'Chinese/Hong Kong SAR',
  'Chinese/Macao SAR',
  'China Taiwan',
] as const;

